name: playwright-commonjs-jasmine-expect

on: 
  push:
  schedule:
    - cron: '0 0 1-31/2 * *' 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Fix broken apt list
      if: matrix == null || matrix.os == 'ubuntu-latest' || matrix.os == 'ubuntu-18.04'
      run: sudo perl -p -i -e 's#16\.04/prod xenial#18.04/prod bionic#' /etc/apt/sources.list.d/microsoft-prod.list{,.save}      
    - name: install required packages
      run: |
        sudo apt-get update
        sudo apt-get install libwoff1 libopus0 libwebp6 libwebpdemux2 libenchant1c2a libgudev-1.0-0 libsecret-1-0 libhyphen0 libgdk-pixbuf2.0-0 libegl1 libgles2 libevent-2.1-6 libnotify4 libxslt1.1
        sudo apt-get install xvfb
    - name: INSTALL PACKAGES
      run: |
        npm ci
      env:
        CI: true
    - name: LINT
      run: |
        npm run lint
    - name: TEST
      run: |
        npm run test
